version: "3.8"
services:
  ollama:
    image: nicofarizano/ollama-preloaded:llama2
    container_name: ollama
    ports:
      - "11434:11434"

  chatbot:
    build:
      context: .
    container_name: promtior-chatbot
    image: nicofarizano/promtior-chatbot
    ports:
      - "11435:11435"
    environment:
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama